### ISSUE TITLE
[BUG] ariaTSsetup.py fails after bbox changed

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools#187]
**Describe the bug**

I previously ran `ariaTSsetup.py` in this directory with a larger bbox `--bbox "25 28 83 86"`. After loading it into MintPy, it failed because there was no data south of 26°N. See https://github.com/insarlab/MintPy/issues/398
I ran `ariaTSsetup.py` again with a smaller  bbox to exclude the area with no data, and it seems to get confused about the area in the masking step, even after I removed the whole `mask` directory and asked it to download again.

**To Reproduce**
1. Download 
`ariaDownload.py --bbox "26 28 83 86" --track 19 -o download`
2. Command used
```
ariaTSsetup.py -f 'products/*.nc' --bbox "25 28 83 86" -d DEM/SRTM_3arcsec.dem --mask download
ariaTSsetup.py -f 'products/*.nc' --bbox "26 28 83 86" -d DEM/SRTM_3arcsec.dem --mask download
```
3. Error Output
```
***Time-series Preparation Function:***
Shapefile ./user_bbox.json created for input user bounds.
Multi-core version
Multi-core version failed, will try single for loop
285 out of 470 GUNW products rejected for not meeting user's bbox spatial criteria
Group GUNW products into spatiotemporally continuous interferograms.
All (163) interferograms are spatially continuous.
Thread count specified for gdal multiprocessing = 2
Download/cropping DEM
***Downloading water mask... ***
Warning 1: HTTP response code on http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip: 0
ERROR 1: Failed to open datasource `/vsizip/vsicurl/http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip/GSHHS_shp/f/GSHHS_f_L3.shp'.
ERROR 1: Failed to open datasource `/vsizip/vsicurl/http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip/GSHHS_shp/f/GSHHS_f_L2.shp'.
ERROR 1: Failed to open datasource `/vsizip/vsicurl/http://www.soest.hawaii.edu/pwessel/gshhg/gshhg-shp-2.3.7.zip/GSHHS_shp/f/GSHHS_f_L4.shp'.

Extracting unwrapped phase, coherence, and connected components for each interferogram pair
Generating: unwrappedPhase - [==================================================] 20200613_20200601    0s /     0s
Generating: coherence - [==================================================] 20200613_20200601  110s /     2s

Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
Generating: incidenceAngle - [==================================================] 20150511_20150429Traceback (most recent call last):
  File "/Users/fielding/anaconda3/envs/aria-tools/bin/ariaTSsetup.py", line 15, in <module>
    main(inps)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/tsSetup.py", line 275, in main
    export_products([dict(zip([k for k in set(k for d in standardproduct_info.products[1] for k in d)], [[item for sublist in [list(set(d[k])) for d in standardproduct_info.products[1] if k in d] for item in sublist] for k in set(k for d in standardproduct_info.products[1] for k in d)]))], standardproduct_info.bbox_file, prods_TOTbbox, layers, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps.num_threads, multilooking=inps.multilooking)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py", line 324, in export_products
    finalize_metadata(outname, bounds, dem_bounds, prods_TOTbbox, dem, lat, lon, mask, outputFormat, verbose=verbose)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/ARIAtools/extractProduct.py", line 647, in finalize_metadata
    out_interpolated = mask.ReadAsArray()*out_interpolated
ValueError: operands could not be broadcast together with shapes (2400,3600) (3600,3600)
```

**Expected behavior**
I expected `ariaTSsetup.py` to create new files for the smaller bbox.

**Screenshots**
This was the output of MintPy for the larger area.
![avgPhaseVelocity](https://user-images.githubusercontent.com/7253576/87238198-6852ae00-c3b4-11ea-865c-7d8686d01ff9.png)

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary]
commit 7d173b0aa2b4a3a6459ac674f253c7e4058b803f (HEAD -> dev, origin/dev, origin/HEAD)
Author: rzinke <48299159+rzinke@users.noreply.github.com>
Date:   Thu Jul 9 18:17:29 2020 -0700
 - OS
MacOS

**Additional context**

**Comment by EJFielding** [comment]
I verified that going back and running the larger bbox works in the same directory. I also was able to run the  `--bbox "26 28 83 86"` stack setup in a new working directory. This is a good workaround, but I still consider this a bug.

**Comment by sssangha** [comment]
@EJFielding yes, the default value for the minimum area threshold is 90km^2 because that is the area of one pixel. So that is to say, the program goes through to completion so long as at least one pixel is spatial coincides with a bounding box, if specified.
 
Each standard product frame is ~42,000 km^2 in area:
<img width="1347" alt="Screen Shot 2020-07-13 at 12 08 08 AM" src="https://user-images.githubusercontent.com/13227405/87279623-eb9ffc80-c4a5-11ea-8c9e-3548b6310e99.png">
 
So your specified minimum threshold of 15,000 km^2 seems conservative enough. See screenshot below of the grey shapefile which represents the intersection of your bounding box (in the foreground in orange) and the common intersection of all valid products, and has a total area of ~42,000 km^2:
<img width="607" alt="Screen Shot 2020-07-13 at 1 07 27 AM" src="https://user-images.githubusercontent.com/13227405/87279583-cd3a0100-c4a5-11ea-874c-4d816a7ce2ef.png">
 
However, if you run the command in verbose mode (just append -v to the end of your input). You will see specifically which products were rejected. E.g.:
```
Rejected scene bbox26_27_5/productBoundingBox/20150523_20150429.json has only 82.590629km² overlap with bbox
Rejected scene bbox26_27_5/productBoundingBox/20150523_20150511.json has only 82.590629km² overlap with bbox
Rejected scene bbox26_27_5/productBoundingBox/20170430_20170406.json has only 5442.633846km² overlap with bbox
…
```
 
If we take a look at a couple of these examples, you will see that they clearly have very small overlap w.r.t. the orange box which represents your input bounding box:
<img width="522" alt="Screen Shot 2020-07-13 at 1 03 54 AM" src="https://user-images.githubusercontent.com/13227405/87279612-e3e05800-c4a5-11ea-9a8d-449552f0e80a.png">
 
So this minimum threshold option is very useful in filtering out scenes that would bias the common intersection with the bounding box such that every product would be cropped to a very small sliver of area. Keep in mind though that the default is to crop all products to the common intersection as I described, but you may alternatively crop your stack to the union of all products with the “--croptounion” option. Of course this option will be too liberal for most applications.
 
Please let me whether or not this all makes sense.

**Comment by sssangha** [comment]
> I verified that going back and running the larger bbox works in the same directory. I also was able to run the `--bbox "26 28 83 86"` stack setup in a new working directory. This is a good workaround, but I still consider this a bug.

It looks like your mask download for the second ariaTSsetup run failed, such that the older mask was then used. I have been unable to replicate this issue though, however I updated PR #186 to raise an exception so that the code exits with a crash instead of continuing and thereby reading the older existing mask. If it is possible to replicate this error, can you please try again with this change to see if the code crashes as I intend?

Also along these lines, unless you are referencing a larger, master DEM/mask of the region, I would suggest you specify a fresh download for each run. It looks like you are referencing the same common DEM for each run, which may no longer span the specified extent with valid data even though it will be warped to your specified extents.

**Comment by EJFielding** [comment]
@sssangha Thanks for the detailed explanations. I have not tried the `-v` or `--croptounion` options. In this case, using the `-mo` option seems the best way to get only the good coverage pairs. 

The DEM and mask downloads take about 10 minutes to finish when I run them from home, so I was trying to avoid that duplication of download. It would be a lot more user-friendly if the `ariaTSsetup` code could check the products that were downloaded previously and use them or re-download if necessary.

**Comment by dbekaert** [comment]
@EJFielding also note that you will not get much data south of 25.75 degrees; as that is the southern most edge of the AOI defined for processing. 
<img width="200" alt="Screen Shot 2020-07-14 at 8 40 42 AM" src="https://user-images.githubusercontent.com/19240905/87446104-b979c200-c5ad-11ea-964d-252c670f090b.png">

Generally i prefer to take a bbox either similar to the AOI track and then force the area overlap constraint to be close to its max area; or take a smaller bbox within that area and again roughly make it the area size for it. That way you will not have pixels come in/go out during time-series processing.

Wrt to the reprocessing and checking files; it is a bit broader than just the DEM and mask files. IT also covers any other file that was extracted. We have been discussing an approach in our slack channel for the last few months. Its on the list but not yet on the top. If i can find some time i will document the proposed approach in a ticket. It will require quite some testing and debugging, to that extent we welcome contributions.

**Comment by dbekaert** [comment]
For now the best practice is to delete and restart unless there are no changes on the BBOX.

**Comment by EJFielding** [comment]
Thanks for the explanations @dbekaert. These best practices could be better explained in the documentation.
