### ISSUE TITLE
ariaDownload.py checks for .netrc or takes input for username and password from command line

### ISSUE THREAD

**Issue by ehavazli** [aria-tools/ARIA-tools#197]
**Is your feature request related to a problem? Please describe.**
One can't pass a username and password but needs to enter manually when prompted.

**Describe the solution you'd like**
Have an option to pass username and password in the command line and/or go check the .netrc file

**Comment by EJFielding** [comment]
Yes, the ISCE package gets the EarthData login information from `$HOME/.netrc`, which is a lot easier to use.

**Comment by bbuzzanga** [comment]
Currently, we are leveraging ASF's bulk download script, which does a couple nice things like handling partial downloads. I'm quite sure there is no way to pass credentials through the `ariaDownload.py` into the underlying bulk download script. However, there should be a way to have it read the `.netrc`. I spent some time recently working on it but was stumped and received radio silence from a query to ASF. Perhaps @davidbekaert has a contact I can try?

Alternatively, it is relatively simple to change `ariaDownload.py` to directly use `wget` or `curl` (rather than wrapping around the bulk download script). By default, these read a `.netrc` and it would be trivial to implement manual credentials.

**Comment by piyushrpt** [comment]
Look at the closed PR on ISCE for staging earthdata products - was a variant of ASF's old bulk downloader. Uses netrc module to load info from .netrc and authenticate

**Comment by dbekaert** [comment]
@bbuzz31 I would like to ensure we keep on using the ful DAAC api capabilities for checksums etc. We jsut need to make sure the cookie is made in advance. the PR  @piyushrpt is referring too is this one: https://github.com/isce-framework/isce2/pull/66

**Comment by EJFielding** [comment]
Would it be possible to have two options? The interactive username and password entry is a big hassle for Jupyter notebooks and prevents any batch processing.

**Comment by bbuzzanga** [comment]
@piyushrpt @dbekaert thanks for pointing me to the ISCE PR. That was very helpful, and I was able to implement it into our `ariaDownload` wrapper. I will implement credential passing so both options are available and issue a pull request in the next couple days.

**Comment by dbekaert** [comment]
> Would it be possible to have two options? The interactive username and password entry is a big hassle for Jupyter notebooks and prevents any batch processing.

That is the plan.
