### ISSUE TITLE
Error on downloading DEM files

### ISSUE THREAD

**Issue by nabolfat** [aria-tools/ARIA-tools#237]
Hi,
I am trying to use ariaTSsetup running the following command:
ariaTSsetup.py -b '35.2 36.2 -118 -117' -f 'products/*.nc' --mask Download -w 'products_ariaoutputs'

The DEM directory is made and is empty, and then I will get the following error message:
"RuntimeError: products_A_t64_ariaoutputs/DEM/SRTM_3arcsec_uncropped.dem.vrt: No such file or directory"
 
The DEM files should be downloaded automatically. I could not figure out why I am getting the error message.
I appreciate it if you can help me with this.

Thanks,
Niloufar

**Comment by dbekaert** [comment]
Changes on opentopo for hosting the DEM. We are looking for a work-around.

**Comment by rzinke** [comment]
Hello, I am running into the same issue. Have there been any recent updates?

**Comment by dbekaert** [comment]
@rzinke, the solution is implemented here: https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/dem.py; would need porting to ARIA-tools in the same way.

**Comment by yuankailiu** [comment]
@dbekaert, @rzinke, is there a way currently to use DEM which is pre-downloaded ourselves before hand (i.e., from [GMRT.org](https://www.gmrt.org/GMRTMapTool/))? 

I also tryied to do the same way as the implementation in [RAiDER](https://github.com/dbekaert/RAiDER/blob/dev/tools/RAiDER/dem.py).

Is it this line in ARIA-tools' extractProduct.py needs to be modified for porting?
`_world_dem = '/vsicurl/https://cloud.sdsc.edu/v1/AUTH_opentopography/Raster/SRTM_GL1_Ellip/SRTM_GL1_Ellip_srtm.vrt'`

I replace it by the following:
`    _world_dem = "https://portal.opentopography.org/API/globaldem?demtype=SRTMGL1_E&south={}&north={}&west={}&east={}&outputFormat=GTiff"`

Do I miss something that it still doesn't work?

**Comment by dbekaert** [comment]
## fix bring own DEM
@liuykai wrt own DEM, just it was always envisioned to be supported, but needs a bug fix see #238.

## fix download internally in ARIA-tools
Wrt porting over the fix from RAiDER here:
1. update the filepath
2. we are not using a vrt access using GDAL anymore rahter we use the opentopo API to download. So you also need to port over: https://github.com/dbekaert/RAiDER/blob/1b674c51316512fea5824e393ffa17ba8d6b7ed4/tools/RAiDER/dem.py#L146-L152
3. Check if the download DEM is GDAL compatible. i.e. do a GDAL info on the file to see if the projection and transformation information is correctly represented.
4. The filename of the downloaded DEM should be set such its called *_uncropped like how its currently being done.

**Comment by dbekaert** [comment]
@nabolfat @liuykai can you give the PR a test to verify it does not break anything you are expecting? #239

**Comment by dbekaert** [comment]
fixed per #239

**Comment by EJFielding** [comment]
The PR worked for me to do a DEM download.

**Comment by nabolfat** [comment]
Mine is working as well! Thanks.

**Comment by yuankailiu** [comment]
Also works perfectly for me, @dbekaert. Thanks for checking and updating.

**Comment by liulinan** [comment]
Hi there,

Since working on a small-size area (settlements of several buildings), I'm trying to download high-resolution DEM files. To my knowledge, 1/3 arc-second or higher resolution DEM files are available at https://viewer.nationalmap.gov/basic/. However, the downloaded files are in a different format. Does anyone know how to use such downloaded DEM files into ariaTSsetup? Or any other suggestions? Thanks in advance~

Linan

**Comment by EJFielding** [comment]
The DEM files are read by ariaTSsetup using GDAL, so you need to get a GDAL ".vrt" file for your DEM. The ARIA standard interferograms have 3-arcsecond (~90 m) resolution, so using very high resolution DEMs won't make a difference in the time-series output.

**Comment by dbekaert** [comment]
As Eric indicates, a GDAL compatible file should the trick (e.g. try a gdalinfo on the file). Also its assumed that the DEM file is ellipsoid corrected for intersection with the geometry information; that would be consistent with how the geometry information was computed. Generally it might be good to use a DEM in case you are aware of inconsistencies in the SRTM DEM v3. The product itself were multi-looked to about 100 m; and geocoded to 90m.

**Comment by liulinan** [comment]
Thanks @EJFielding and @dbekaert ,
The reason I'm trying to use high resolution DEMs is the result I got looks like this. It looks speckled, rather than a smooth contour. Do you know what's going wrong? I guessed it may because of low resolution DEMs. But I'm not sure. 
<img width="208" alt="Picture1" src="https://user-images.githubusercontent.com/60360410/99333667-c8170500-283d-11eb-9f94-1f128ea24192.png">

**Comment by EJFielding** [comment]
I can see your velocity has pixels that are about 90 m across, so that is the resolution of the ARIA standard products. The speckle pattern means there is a lot of noise in the interferograms here. If you are including interferograms with long time intervals, then restricting your time-series analysis to interferograms with shorter intervals might help.

**Comment by liulinan** [comment]
Got it, thanks @EJFielding. I'll try to shorten time intervals.
