### ISSUE TITLE
Adding a version number for ARIA-tools

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#263]
perhaps for released version add a version number.

Perhaps for GitHub dev version report the tag of the latest commit and date of the tag.
Print this input for each ARIA-tools main run.
This will make it easier on OSL and debugging.

**Comment by bbuzzanga** [comment]
I've added this feautre in #269. 

It's not fully correct, in that it gets version v1.1.0 instead of 1.1.1, but this is problem with the git history.

If you run `git log --no-walk --tags --pretty="%h %d %s" --decorate=full`, you'll see the three tagged versions, and that the latest version is tagged to commit `45ebfb5`. You can check out `45ebfb5` with no problem (`git checkout 45ebfb5`).

But if you look through just do `git log` you won't be able to find the commit. It maybe time to make a new branch with a clean rebase, make a new version and make this the default branch.

**Comment by dbekaert** [comment]
ok if we can do a brief test and document the **version** of ARIA-tools and mintpy that is compatible then we can cut new release,
