### ISSUE TITLE
tropo support 

### ISSUE THREAD

**Issue by dbekaert** [aria-tools/ARIA-tools#334]
Adding in support for tropo:

- [x] add tropo as layer to the interface here (note there is a hydro, wet and perhaps we could say total): https://github.com/aria-tools/ARIA-tools/blob/438e3e6a1853f688c8431d4c2a97ba181d09bed6/tools/ARIAtools/extractProduct.py#L54
- [x] add in tropo group under 1c version here: https://github.com/aria-tools/ARIA-tools/blob/438e3e6a1853f688c8431d4c2a97ba181d09bed6/tools/ARIAtools/ARIAProduct.py#L419 
- [x] add tropo in the sds keys here: https://github.com/aria-tools/ARIA-tools/blob/438e3e6a1853f688c8431d4c2a97ba181d09bed6/tools/ARIAtools/ARIAProduct.py#L263
- [x] Add tropo to the group the condination to extract 2D from 3D here: https://github.com/aria-tools/ARIA-tools/blob/438e3e6a1853f688c8431d4c2a97ba181d09bed6/tools/ARIAtools/extractProduct.py#L614

**Comment by dbekaert** [comment]
The above is all addressed in the PR#335. Thanks @sssangha; this will help with test and development on the raider and gunw side.

Few more point for discussion 
1. I don't think we should be correcting the unwrapped phase when tropo is requested, rather only extract it. So default behavior of GACOS of correcting the phase and passing to mintpy is not desired.
2. For the aria extract layers option could have the three flavors in it.
3. i think for TS prep towards mintpy it should only take the total delay.
4. When now going into MintPy i would suggest we have the IFG stack cube of tropospheric corrections (e.g. unw, coh, connComp and now also a tropo stack). 
       - @yunjunz any guidance here? Also would be good to be backward compatible if that tropo dataset is not specified/generated that the mintpy code still runs.

**Comment by sssangha** [comment]
@yunjunz for context, for instance currently if a user had specified 'GACOS corrections' through ARIA-tools, corrections would be applied to the unw phase through ARIA-tools itself as opposed to leveraging mintpy. So the intention now is to update 'prep_aria.py' to leverage mintpy to perform tropo corrections, be it may derived from raider or gacos. Make sense? Thanks!

**Comment by yunjunz** [comment]
For the output file, e.g. from prep_aria.py, I would recommend writing the GACOS delay (in LOS) into an independent time-series HDF5 file, which contains the absolute tropospheric delay for each acquisition, a.k.a., no reference in time or space, for maximum compatibility. This is what the current `tropo_gacos.py` produces.

For the code itself, `prep_aria.py` could leverage the [`tropo_gacos.calculate_delay_timeseries()`](https://github.com/insarlab/MintPy/blob/541f33c316252e7c8ab72b0c38425b1bedabeb4d/src/mintpy/tropo_gacos.py#L95) to turn a list of GACOS files into a time-series, with a few modifications, e.g. accommodate the file format from `TSsetup`, use a list of date instead of an existing TS file as input, etc.

**Comment by dbekaert** [comment]
@yunjunz The ARIA product is under-going an update to replace the placeholder layers with data. We are adding in the tropo, iono, solid earth tides, dense-offsets etc all of which are differential given the product (the absolute nature is thus lost within the product). This would make them pretty much consistent with the NISAR GUNW design.

By inverting it ahead of time we are making assumption about which date does not have delay. Is there a way to feed it similar like coh, unw etc. 

Seperately do you have suggestion how we should feed stacks of:
- ionosphere
- solid earth tides
- dense offsets

Thanks for your guidance and thoughts.

**Comment by yunjunz** [comment]
For troposphere, ionosphere and solid Earth tides, I assume they are in the unit of radian? If so, the easy way could be to load each of them into an independent stack HDF5 file, e.g. tropStack.h5, ionStack.h5, etc., under the group name of `ifgramStack` and dataset name of `unwrapPhase`. So all of them will have the same internal structure, but different file names to distinguish among themselves.

@yuankailiu has been playing with `ionStack.h5` in mintpy from topsStack for a while now, using: https://github.com/insarlab/MintPy/blob/541f33c316252e7c8ab72b0c38425b1bedabeb4d/src/mintpy/defaults/smallbaselineApp.cfg#L42-L45. The idea is to invert the stack into time-series with the simplest configurations (no weighting).

It makes sense if one applies all these corrections in the interferogram stage, then inverts for the time-series. TBH, I don't get the benefit of loading the stack of solid Earth tides from ARIA into mintpy, since the TS can be easily generated within mintpy. And keep in mind that the stack h5 file is usually big, usually accounting for >50% of the entire mintpy time-series analysis.

As for the dense offsets, assuming in the unit of pixel, they can be loaded into another stack HDF5 file, e.g., offsetStack.h5, under the same `ifgramStack` group name but with different dataset name, rangeOffset and azimuthOffset. I have been using these for my geolocation for a couple of years now, using the following template options (based on topsStack and stripmapStack): https://github.com/insarlab/MintPy/blob/541f33c316252e7c8ab72b0c38425b1bedabeb4d/src/mintpy/defaults/smallbaselineApp.cfg#L46-L51

My stack file structure is as below for your reference:
```
/ifgramStack            - top-level group name
    /rangeOffset        - dataset name
    /rangeOffsetStd
    /azimuthOffset
    /azimuthOffsetStd
    /offsetSNR
```

@yuankailiu and I have been adjusting the mintpy code to recognize these file structures (for ionStack.h5 and offsetStack.h5) automatically.

**Comment by dbekaert** [comment]
wrt inclusion of layers: We are moving towards a self-contained ARD product for InSAR that has all layers embedded, as what is being recommended under CEOS CARD4L. Honestly there is no need to keep for example the solid earth tides, ocean tides or even tropo at full resolution within a product. The impact for ARIA GUWN product size is relative small, for users using different packages it becomes a one-stop-shop product. Only the full res ionosphere or the dense-offsets is what adds currently in file size.

Guidance looks pretty clear, few extra questions:
- We will need to do some internal work as we also need to stitch the ionosphere. Do you internally in mintpy work on correcting any artifacts in ionosphere or use it as is. e.g. when labeling the unwrap class does it need to have a connected component?
- I understand correctly, that for mintpy compatibility dense offsets should not be in meter units, nor should they be projected.

**Comment by yunjunz** [comment]
The one-stop-shop product sounds great!

> We will need to do some internal work as we also need to stitch the ionosphere. Do you internally in mintpy work on correcting any artifacts in ionosphere or use it as is. e.g. when labeling the unwrap class does it need to have a connected component?

mintpy use as it is currently. The connected components and coherence dataset from ionosphere is not really used. @yuankailiu correct me if I am wrong please.

> I understand correctly, that for mintpy compatibility dense offsets should not be in meter units, nor should they be projected.

I did not think of the choices carefully before, thus, chose the native unit of pixel from isce2; and converted this unit to meters in slant range direction and ground azimuth direction when inverting for the time-series. Having this conversion done in the very beginning sounds equally good to me.
